"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";

// const interDisplay = localFont({
//   src: [
//     {
//       path: './fonts/InterDisplay-Regular.ttf',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: './fonts/InterDisplay-Medium.ttf',
//       weight: '500',
//       style: 'normal',
//     },
//     {
//       path: './fonts/InterDisplay-Bold.ttf',
//       weight: '700',
//       style: 'normal',
//     },
//   ],
// })

const queryClient = new QueryClient()

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AuthProvider>
        <QueryClientProvider client={queryClient}>
        {children}
        <Toaster />
        </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
